name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  APP_NAME: app-debug
  JAVA_VERSION: '11'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: $JAVA_VERSION
        distribution: 'temurin'
        cache: gradle
  
    - name: Run Kotlin Linter
      uses: ScaCap/action-ktlint@master
      with:
        github_token: ${{ secrets.TOKEN_FOR_GITHUB }}
        android: true
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: bash ./gradlew assembleDebug
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: $APP_NAME
        path: app/build/outputs/apk/debug/$APP_NAME.apk
  deploy:
    needs: build
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: app-debug
        
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: test-team
          file: app-debug.apk
